# fly.toml app configuration file generated for polished-wind-2400 on 2023-07-10T11:17:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "polished-wind-2400"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
